name: Trips 

on:
  push:
    branches: [ main ]
    paths: 
      - apis/trips/**  
      - .github/workflows/trips.yml
  pull_request:
    branches: [ main ]
    paths: 
      - apis/trips/**  
      - .github/workflows/trips.yml

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go get

    - name: Run Unit Tests
      run: go test ./tripsgo -run Unit
