name: Trips 

on:
  push:
    branches: [ main ]
    paths: 
      - apis/trips/**  
      - .github/workflows/trips.yml
  pull_request:
    branches: [ main ]
    paths: 
      - apis/trips/**  
      - .github/workflows/trips.yml

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: apis/trips
        
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Install dependencies
      run: go get

    - name: Run Unit Tests
      run: go test ./tripsgo -run Unit
     #run: go test ./tripsgo
     
    - name: Create Issue on Failed Workflow
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: Action workflow failed.
        body: |
          ### Context
          [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
          Workflow name - `${{ github.workflow }}`
          Job -           `${{ github.job }}`
          status -        `${{ job.status }}`
